# Generated by Django 4.1.7 on 2023-03-01 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Request",
        ),
    ]
